# Site settings
title: CRNC.work
email: MarkBruns@MarkBruns.com
description: Commitgraph-driven workflow and proof-of-work, distributed ledgers and mechanisms like memecoins to reinforce good habits with the currency of reputation and communication improvement for 10X-er time mgmt 
twitter_username: MarkBruns
github_username:  CRNCwork

# Build settings
markdown: kramdown
