# Site settings
title: CRNC.work
email: MarkBruns@MarkBruns.com
description: Fork the CRNC.work repositories; make them your own.
twitter_username: MarkBruns
github_username:  CRNCwork

# Build settings
markdown: kramdown
