# Site settings
title: CRNC.work
email: MarkBruns@MarkBruns.com
description: Commitgraph-driven workflow, currency of reputation, proof-of-work, distributed ledgers and mechanisms like memecoins, communication improvement and 10X time mgmt 
twitter_username: MarkBruns
github_username:  CRNCwork

# Build settings
markdown: kramdown
